### PR TITLE
Shows icons of what permissions each user has in the settings page

### PR DESCRIPTION
**Pull request by jwar663**
#### Description
Added icons to show what permissions each user has in a given project.
Wrench=admin
People=Collaborator
Eye=Observer

#### Review Checklist
- [x] The requirements on the description have been met
- [x] The relevant documentation has been updated:
    - [x] code comments for classes / methods / complex statements
    - [x] package readme
    - [x] documentation for high level approaches or product info
- [x] Tests:
    - [ ] new tests written
    - [ ] existing affected tests updated
    - [ ] all green and passing
- [ ] Tested by reviewer

### CODE REVIEW

**Comment by RajanGuptaNZ** [comment]
Tested. Works for me :)
Only problem is I get these errors, might be due to being out of date with master?

image

**Comment by jwar663** [comment]
> Tested. Works for me :)
> Only problem is I get these errors, might be due to being out of date with master?
> 
> image

Updated from master, it still works, errors are gone.

**Comment by Akrya** [comment]
> > Tested. Works for me :)
> > Only problem is I get these errors, might be due to being out of date with master?
> > image
> 
> Updated from master, it still works, errors are gone.

LGTM. Not getting those errors anymore and it works fine.

**Review by Akrya — APPROVED** [review]
👍👍

**Pull request merged**
