### PR TITLE
Bugfix/document export

### PR DESCRIPTION
**Pull request by tnzhu**
#### Description
Added the token checking to the export endpoint
Changed exporting of csv to version where csv file is created locally 

#### Review Checklist
- [x] The requirements on the description have been met
- [x] The relevant documentation has been updated:
    - [ ] code comments for classes / methods / complex statements
    - [ ] package readme
    - [ ] documentation for high level approaches or product info
- [x] Tests:
    - [ ] new tests written
    - [ ] existing affected tests updated
    - [ ] all green and passing
- [ ] Tested by reviewer

### CODE REVIEW

**Review by saddboys — CHANGES_REQUESTED** [review]
Works as intended, but exports should be limited to only participants of a project, someone not involved with a project should not be allowed to export. Thanks

**Comment by saddboys** [comment]
image

As per this image, trying to export a file sometimes causes this bug, please fix this as well!

**Comment by tnzhu** [comment]
> image
> 
> As per this image, trying to export a file sometimes causes this bug, please fix this as well!

A previous commit was applied to fix the bug, it works on my system, so might be an OS thing? Would be nice if everyone could test and see what they get

**Review by jwar663 — APPROVED** [review]
LGTM

**Review by saddboys — APPROVED** [review]
looks fine

**Pull request merged**
