### PR TITLE
Frontend/settings page enhancement

### PR DESCRIPTION
**Pull request by xoneon**
#### Description
Settings page UI overhaul.
Tags on left side, users on right side. Changes to Tags on top and Users on bottom if screen width is small.
Users is now a table with pagination (5 users per page)
Tags look changed (border-radius is 13px)
Now a single title ("[project name] Settings") instead of two titles
Removed title for user list, should be self explanatory

#### Review Checklist
- [ ] The requirements on the description have been met
- [ ] The relevant documentation has been updated:
    - [ ] code comments for classes / methods / complex statements
    - [ ] package readme
    - [ ] documentation for high level approaches or product info
- [ ] Tests:
    - [ ] new tests written
    - [ ] existing affected tests updated
    - [ ] all green and passing
- [ ] Tested by reviewer

### CODE REVIEW

**Comment by mliu433** [comment]
Nice work, could you make the tag section a bit prettier, please

**Review by mliu433 — CHANGES_REQUESTED** [review]
move the add user to the first column or you can have a look at this design, add table header on the top of columns [https://dribbble.com/shots/3272274-Manage-app/attachments/703699](url)

**Comment by mliu433** [comment]
make add tag align to the right, also make the tag on the tag with the same width

**Comment by xoneon** [comment]
@mliu433 
- why align to the right? I think it looks better in the middle, otherwise there's lots of empty space on the left
- what do you mean by "make the tag on the tag with the same width"?

**Comment by xoneon** [comment]
tag column will not move position now.

**Review by mliu433 — APPROVED** [review]

**Pull request merged**
