### PR TITLE
Feature/unconfirmed documents

### PR DESCRIPTION
**Pull request by Cvos0162**
#### Description
render unconfirmed documents

#### Review Checklist
- [ ] The requirements on the description have been met
- [ ] The relevant documentation has been updated:
    - [ ] code comments for classes / methods / complex statements
    - [ ] package readme
    - [ ] documentation for high level approaches or product info
- [ ] Tests:
    - [ ] new tests written
    - [ ] existing affected tests updated
    - [ ] all green and passing
- [ ] Tested by reviewer

### CODE REVIEW

**Review by saddboys — CHANGES_REQUESTED** [review]
I get this error when trying to access the unconfirmed 
image
Please make sure that unconfirmed tab is only accessible by contributors (possible same for unlabeled)

**Comment by Cvos0162** [comment]
> I get this error when trying to access the unconfirmed
> image
> Please make sure that unconfirmed tab is only accessible by contributors (possible same for unlabeled)

changed

**Review by saddboys — APPROVED** [review]
image
make this 1 instead of not a number please

**Review by saddboys — CHANGES_REQUESTED** [review]
image
When switching to the unconfirmed page, please fix this as well

**Comment by Cvos0162** [comment]
> image
> When switching to the unconfirmed page, please fix this as well

I tried to followed what you have said, but the error didn't show up. I think I just have done now would fix it so can you test it again?

**Review by saddboys — APPROVED** [review]

**Pull request merged**
